# Generated by Django 3.2.12 on 2022-02-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='users', serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=50, unique=True)),
                ('second_name', models.CharField(max_length=50, unique=True)),
                ('profile_pic', models.ImageField(upload_to='profile_pics')),
                ('bio', models.TextField()),
                ('joined_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-joined_on'],
            },
        ),
    ]
