# Generated by Django 3.2.12 on 2022-02-14 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('comment_article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_of_comment', to='app.article')),
                ('comment_author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
